/*
 * PatchBlock: {{ .Name }}
 * {{ .Username }} - {{ .DateNow }}
 *
 * Generated by pbgen https://github.com/twhiston/pbgen
 *
 * data->
{{- if .Inputs -}}
{{- range $key, $value := .Inputs }}
 *      *in{{ $key }}
{{- end -}}
{{- end -}}
{{ if .Outputs -}}
{{- range $key, $value := .Outputs }}
 *      out{{ $key }}
{{- end -}}
{{- end -}}
{{ if .Vars -}}
{{- range $key, $value := .Vars }}
 *      {{ $value.Name }} ({{ $value.Dtype }})
{{- end -}}
{{- end }}
 */
static inline void i{{ len .Inputs }}o{{ len .Outputs }}_{{ .Name }}(i{{ len .Inputs }}o{{ len .Outputs }} *data){

    /* Implement the special sauce here */

}
